### ISSUE TITLE
Asset Thumbnails

### ISSUE THREAD

**Issue by imjakechapman** [nfourtythree/craft-json-data#1]
Is there a way of retrieving a CP transform for an image asset and merging it into an entry's json?

**Comment by nfourtythree** [comment]
I had a little guess at what you might need and updated the plugin.

Taken from the readme below this should hopefully get you to where you need to be.

It was done really quickly so could be buggy! Hope it helps

---

Added the ability to return Asset transforms by using getUrl() with the handle and returns it in the array

```
// Template Tag
{{ entries | jsonData(
                "id",
                "image.getUrl('myTransformHandle')") | raw }}



// Returns
{
    {
        "id": 1,
        "image":  [
            {
                "myTransformHandle": "http://example.craft.dev/upload/path/_myTransformHandle/image.jpg"
            }
        ]
    }
}
```

**Comment by imjakechapman** [comment]
Awesome, I'm now using this. But seems that it only works on multiple entries. When I'm calling my single entry api route /api/sections/episode/some-entry-title with `craft.entries.section('article').slug(slug).first` I'm getting the error  `PHP Notice: Trying to get property of non-object`. But if I remove the .first and it spits back a single object in an array `[{}]` all works fine but the client side is expecting an object not an array.

Any ideas?

**Comment by imjakechapman** [comment]
Also, I noticed that most number attributes are all passed back as integers but the client-side framework I'm working with and I think backbone as well requires id's to be strings. Anyway of changing the type to a string to not have to mess with the data when parsing it in javascript?

**Comment by nfourtythree** [comment]
I have updated it so you can now pass a single entry and the filter will return an object as you would expect. Hope this helps!

**Comment by imjakechapman** [comment]
Awesome, exactly what I needed! Thank you!
